### ISSUE TITLE
Error 101: object not found for get

### ISSUE THREAD

**Issue by origds** [adelevie/parse-ruby-client#173] opened 2015-06-18 19:11 UTC
I installed parse-ruby-gem putting this line on the gemfile: 

gem 'parse-ruby-client', git: 'https://github.com/adelevie/parse-ruby-client.git'

And the I had run bundle update parse-ruby-client

It installed gem version 0.3.0, that not have the Installation's get method apparently. I need to use this method for update the badge number for push notifications.

Please, can anyone help me with this?

**Comment by rhymes** [comment] 2015-06-18 23:02
duplicate of #162

**Closed by rhymes** 2015-06-18 23:02 UTC
